import Head from "next/head"
import { GetServerSideProps } from "next"
import dbConnect from "lib/dbConnect"
import Recipe from "models/Recipe"
import Step from "models/Step"
import Category from "models/Category"
import Comment from "models/Comment"
import Ingredient from "models/Ingredient"
import RecipeShow from "@/components/RecipeShow"
import CommentsSection from "@/components/CommentsSection"

 

export default function index({ recipe, ingredients , categories, steps, comments }) {
    
    return (
        <div>
            <Head>
            <title>  </title>
            <meta name="description" content="Generated by create next app" />
            </Head>
            <div className="flex-column">
                <RecipeShow recipe={recipe} ingredients={ingredients} categories={categories} steps={steps} />
                <CommentsSection recipe={recipe} comments={comments}/>
            </div>
        </div>
    )
}

export const getServerSideProps : GetServerSideProps = async ({params}) => {
   
    await dbConnect();
    require("../../models/User");
    const recipe = await Recipe.findById(params.id).lean().populate('author').exec()

    const ingredients = await Ingredient.find({}).where('recipe_id').equals(recipe._id).lean()
    const categories = await Category.find({}).where('recipe_id').equals(recipe._id).lean()
    const steps = await Step.find({}).where('recipe_id').equals(recipe._id).lean()
    const comments = await Comment.find({}).where('recipe_id').equals(recipe._id).lean().populate('user_id').exec()

    return {props: { 
        recipe:   JSON.parse(JSON.stringify(recipe)), 
        ingredients: JSON.parse(JSON.stringify(ingredients)),
        categories: JSON.parse(JSON.stringify(categories)),
        steps: JSON.parse(JSON.stringify(steps)),
        comments: JSON.parse(JSON.stringify(comments)),
    }}
}